language: python
python:
  - "3.9.1"
install: make install
script: make test
branches:
  only:
  - main
notifications:
  email:
    recipients:
      - kalyons@mit.edu
    on_success: never
    on_failure: always
