#!/bin/bash
#
# Descripton
#
# Quick script to go to a particular location on my machine without having to
# type the full path via cd ..
#
# Usage
#
# goto <key>

# Get the key
key=$1

# Check it
if [ "$1" == "nodal" ]; then
    cd ~/Documents/mit/professional/nodal
elif [ "$1" == "nodal-dash" ]; then
    cd ~/Documents/mit/professional/nodal/code/nodalWebApp/dashboardApp
elif [ "$1" == "home" ]; then
    cd ~
elif [ "$1" == "kevin" ]; then
    cd ~/Documents/mit/other/kevin
elif [ "$1" == "mit" ]; then
    cd ~/Documents/mit/
elif [ "$1" == "prof" ]; then
    cd ~/Documents/mit/professional
elif [ "$1" == "secure" ]; then
    cd ~/Documents/__secure__
elif [ "$1" == "courses" ]; then
    cd ~/Documents/mit/courses
elif [ "$1" == "004" ]; then
    cd ~/Documents/mit/courses/6.004
elif [ "$1" == "009" ]; then
    cd ~/Documents/mit/courses/6.009
elif [ "$1" == "042" ]; then
    cd ~/Documents/mit/courses/6.042
elif [ "$1" == "magic" ]; then
    cd ~/Documents/mit/courses/21a.520
elif [ "$1" == "this" ]; then
    open ~/Documents/mit/other/kevin/scripts/goto
elif [ "$1" == "web" ]; then
    cd ~/web
else
    # Unrecognized
    echo "Unrecognized key. Try again."
fi