#!/bin/bash
#
# Descripton
#
# Quick script to push all local changes to a github repo with a default
# message, "Quick commit.". Uses the current local branch @ HEAD.
# 
# Usage
#
# quick-git <heroku>
#
# Notes
#
# Must be run in a git repository, naturally.

git status
git add -A
git commit -m "Quick commit."
git push origin HEAD

# Handle Heroku case for web dev
if [ ! -z "$1" ]; then
    if [ "$1" == "heroku" ]; then
        git push heroku master
    else
        echo "Unrecognized command line argument. Try again."
    fi
fi